# SOME OTHER METHODS ARE
# INDEX() -> ACCESSNIG THE INDEX ValueError
# COUNT() -> COUNT THE NUMBER OF ELEMENTS IN THE LIST
# REVERSE() -> REVERSE THE LIST
# SORT() -> SORT THE LIST IN ASCENDING ORDER OR DESCENDING ORDER 
# COPY() -> CREATE A COPY OF THE LIST

